




.build/uno/src/MatriceLED.cpp : src/MatriceLED.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/MatriceLED.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/MatriceLED.cpp
	@true

